In [25]:
import pandas as pd
import numpy as np

## Q1. Pandas version

In [2]:
pd.__version__

'3.0.5'

## Q2. Records count

In [3]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [4]:
df.shape

(10000, 11)

## Q3. Fuel types

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [6]:
df.fuel_type.nunique()

3

## Q4. Missing values

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Q5. Max fuel efficiency

In [8]:
df[df["origin"]== "Asia"].fuel_efficiency_mpg.max()

np.float64(41.2)

## Q6. Median value of horsepower

In [9]:
df.horsepower.median()

np.float64(254.0)

In [10]:
df.horsepower.value_counts()

horsepower
252.0    174
246.0    168
256.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [11]:
df.horsepower.fillna(252)

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [12]:
df.horsepower = df.horsepower.fillna(252)

In [13]:
df.horsepower.isna().sum()

np.int64(0)

In [14]:
df.horsepower.median()

np.float64(252.0)

## Q7. Sum of weights

In [16]:
df_asia = df[df.origin == "Asia"]

In [17]:
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [20]:
X = df_asia[["vehicle_weight", "model_year"]].head(7).values

In [21]:
X.shape

(7, 2)

In [22]:
XTX = X.T.dot(X)

In [26]:
XTX_inv = np.linalg.inv(XTX)

In [29]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [32]:
w = XTX_inv.dot(X.T).dot(y)

In [33]:
w

array([0.13644777, 0.2327492 ])

In [34]:
w.sum()

np.float64(0.36919696904925486)